var GET_LIST_OF_SOLUTIONS_REQUEST = 'GET_LIST_OF_SOLUTIONS_REQ';
var GET_LIST_OF_SOLUTIONS_RESPONSE = 'GET_LIST_OF_SOLUTIONS_RES';

var SET_SOLUTION_REQUEST = 'SET_SOLUTION_REQ';
var DELETE_SOLUTION_REQUEST = 'DELETE_SOLUTION_REQ';


var GET_CODE_TEXT_REQUEST = 'GET_CODE_TEXT_REQ';
var GET_CODE_TEXT_RESPONSE = 'GET_CODE_TEXT_RES';
var SET_CODE_TEXT_REQUEST = 'SET_CODE_TEXT_REQ';
var SET_CODE_TEXT_RESPONSE = 'SET_CODE_TEXT_RES';


var EXPORT_TO_FILE_REQUEST = 'EXPORT_TO_FILE_REQ';
var IMPORT_FROM_FILE_REQUEST = 'IMPORT_FROM_FILE_REQ';